version: '3'
services:
  supat_backend:
    build:
        context: .
    container_name: supat_backend
    restart: always
    user: root
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:latest
    container_name: supat_backend_nginx
    working_dir: /var/www
    restart: always
    user: root
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8021:80
    depends_on:
      - supat_backend